services:
  nginx:
    container_name: semantic_bot_nginx
    build:
      context: ./apps/client
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    volumes:
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /app/node_modules
      - ./apps/client:/app
    ports:
      - 80:80

  api:
    container_name: semantic_bot_api
    build:
      dockerfile: Dockerfile.prod
      context: ./apps/server
    volumes:
      - /app/node_modules
      - ./apps/server:/app
      - ./data:/data
    env_file:
      - ./apps/server/.env
    restart: always
    ports:
      - 6969:6969
